variable "pep_vnet_name" {}
variable "subresource_names" {}
variable "location" {}
variable "rg_name" {}
variable "subnet_endpoint_name" {}
variable "pep_name" {}
variable "pep_manual_conn" {}
variable "private_zone_id" {}
variable "private_conn_name" {}
variable "network_rg_name" {}
variable "private_conn_id" {}
