name: Linting check

on:
  pull_request:
    branches:
    - 'main'
    - 'release/*'
    - 'hotfix/*'

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.44.1
        github_token: ${{ secrets.FTDS_TFLINT_REPO_ACCESS }}

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --recursive -f compact --disable-rule terraform_typed_variables
